#!/usr/bin/env python
import sys
from itertools import permutations
import math


def nbackseq(n, length, words):
    perm = permutations(words, n)

    for i in list(perm):
        print(",".join((i * math.ceil(length / n))[:length]))

if __name__ == '__main__':
    n = int(sys.argv[1])
    length = int(sys.argv[2])
    words = sys.argv[3:]

    if (len(set(words))< len(words)):
        raise Exception("Invalid Input, all words have to be unique")

    nbackseq(n, length, words)
